apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
namespace: default
images:
- name: backend
  newName: 419656091143.dkr.ecr.us-east-1.amazonaws.com/movie-picture-pipeline-backend
  newTag: 7818c2353ef9d3fb702b44ca6bf5af1369ce7f77
