# Workflow name
name: Backend Continuous Integration

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
      - '.github/workflows/backend-cd.yaml'      

defaults:
  run:
    working-directory: ./starter/backend

# Jobs defined in the workflow
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install  

      - name: Install dependencies flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Linter
        run:  pipenv run lint

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Dependencies
        run: pipenv install

      - name: Install dependencies flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run tests
        run: pipenv run test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Dependencies pipenv
        run: pipenv install

      - name: Install dependencies flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Build Docker Image via CLI
        run: |
          docker build -t mp-backend:latest .
          docker images
          docker run -p 5000:5000 --name mp-backend -d mp-backend
          curl http://localhost:5000/movies
          docker logs -f mp-backend
          docker ps
          docker stop mp-backend