# Workflow name
name: Frontend Continuous Deployment

# Triggers for the workflow
on:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
      - '.github/workflows/frontend-cd.yaml'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./starter/frontend

env:
  AWS_REGION: us-east-1                    # Replace with your AWS Region
  EKS_CLUSTER_NAME: cluster                # Replace with your EKS cluster name
  ECR_REGISTRY: 419656091143.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: movie-picture-pipeline   # Replace with your Amazon ECR repo name

# Jobs defined in the workflow

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Node.js 
        run : npm ci

      - name: Run linter
        run: npm run lint

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies 
        run : npm ci

      - name: Run tests
        run:  CI=true npm test

  deploy-job:
    name: Build, Push and Deploy
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
       
      - name: Build and push image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REACT_APP_MOVIE_API_URL: http://localhost:5000
        run: |
          docker build --build-arg REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

       # Installs Kustomize and adds it to $PATH
      - name: Setup Kustomize
        uses: syntaqx/setup-kustomize@v1
        #with:
          kustomize-version: 'latest'

       # Verify kustomize installation and set the image tag.
      - name: Run Kustomize
        run: |
          kustomize version
          kustomize edit set image backend=${IMAGE_URI}
        working-directory: ./starter/frontend/k8s

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        id: install-kubectl
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./starter/frontend/k8s/kubeconfig.yaml
          kubectl version --client
          kubectl apply -f deployment.yml --kubeconfig=kubeconfig.yaml
        working-directory: ./starter/frontend/k8s